apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: secret/postgres-password
    - secretKey: postgresql-replication-password
      remoteRef:
        key: secret/postgresql-replication-password