apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: postgres
spec:
  provider:
    azurekv:    
      authType: managedIdentity 
      identityId: "$Managed_Identity_ClientId"
      vaultUrl: https://POSTGRES-VAULT-NAME.vault.azure.net/
